### ISSUE TITLE
Bar not visible when using Microsoft's new Remote - SSH extension

### ISSUE THREAD

**Issue by JtMotoX** [Gruntfuggly/activitusbar#16]
When connected to a remote host using Microsoft's new 'Remote - SSH' extension, this activity bar is not present.
![image](https://user-images.githubusercontent.com/7191259/59488551-be14f980-8e34-11e9-96e7-3464b63c36f6.png)

**Comment by MotoX450** [comment]
To answer my own question, it seems that you have to install the extension on each remote host that you are connecting to.  I see that some extensions require this and some don't so not sure what determines this.

![image](https://user-images.githubusercontent.com/7191259/59490686-3205d080-8e3a-11e9-96f3-e1104de5f612.png)

**Comment by Gruntfuggly** [comment]
I don't use remote hosts, so I'm afraid I'm not sure what is required for this. If you can determine the solution, I'm happy to implement it - but I might need you to test.

**Comment by subhav** [comment]
This seems to be the appropriate documentation: https://code.visualstudio.com/api/advanced-topics/remote-extensions#architecture-and-extension-kinds

For whatever reason, the Activitus Bar is classified as a "workspace extension", which means that in order to use it with a remote workspace, you have to install the extension on the remote host as well.

It seems like you should be able to manually override this with `"extensionKind": ["ui", "workspace"]` in package.json: https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location

I can confirm this works when I add the following to my local settings.json:
```
"remote.extensionKind": {
    "gruntfuggly.activitusbar": ["ui"]
},
```

**Comment by Gruntfuggly** [comment]
I've merged the pull request. Please let me know if it works as expected.

**Comment by JtMotoX** [comment]
@Gruntfuggly, Yes I have tested it and it works.  Thank you!


@subhav, I found a simple workaround for extensions that do not yet support this.  You simply place this in your settings.json and add whichever extensions you want to be available without installing on the remote host ([docs](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location)).

```
"remote.extensionKind": {
    "oderwat.indent-rainbow": ["ui", "workspace"],
    "compulim.vscode-clock": ["ui", "workspace"],
    "chrisdias.vscode-opennewinstance": ["ui", "workspace"],
    "mohsen1.prettify-json": ["ui", "workspace"]
},
```

Sorry for hijacking this issue but wanted to get this out there for any users that come across this.
