### ISSUE TITLE
Search not collapsing correctly when search view position is toggled

### ISSUE THREAD

**Issue by Tadaboody** [Gruntfuggly/activitusbar#5]
#### Steps to reproduce:
1. Open search view
2. Right click -> Toggle Search View Position
3. Click Activitusbar search icon multiple times

#### Expected behaviour:
Search view (and the whole terminal group) toggles
#### Resulting behavour:
Search is focused and sidebar visibility is toggled

**Comment by Tadaboody** [comment]
https://github.com/Gruntfuggly/activitusbar/blob/5ace0ecc13b73aeaff4459f13502dc4dd7a8fbe3/extension.js#L53
This line is probably the reason, there could be a check on whether the selected view is part of the sidebar and toggle the correct view.

**Comment by Gruntfuggly** [comment]
Unfortunately you've found the limitations of what the API provides. I can add a setting to not toggle the side bar visibility if you like? but I can't make it toggle the search pane when it is not in the standard position. It's not even possible to determine which view is currently visible. 8-(

**Comment by Gruntfuggly** [comment]
Actually, the above is not completely true. 8-) 

Try the latest version - I've added two flags:
- toggleSidebar: Set this to false to stop toggling when a button is clicked again
- searchViewInPanel: Set this to true when the search view is moved.

You probably only want to set the second one to true - remember to set it back to false if you put the search view back in the side bar, otherwise off stuff will happen!
